-- Additive catalog text and per-field history; no submission tables are touched.
ALTER TABLE pricing_items ADD COLUMN short_label TEXT;
ALTER TABLE pricing_items ADD COLUMN description TEXT;
ALTER TABLE pricing_audit ADD COLUMN field TEXT NOT NULL DEFAULT 'price';
ALTER TABLE pricing_audit ADD COLUMN old_value TEXT;
ALTER TABLE pricing_audit ADD COLUMN new_value TEXT;

-- Current Builder strings, generated by scripts/generate-pricing-seed.mjs --catalog-text.
-- Existing qbb label was already renamed by 0007; do not rewrite that migration.
-- BEGIN GENERATED CATALOG TEXT
UPDATE pricing_items SET label = 'HVAC Care Plan', short_label = 'HVAC', description = 'Stay on top of your homes heating and cooling maintenance with seasonal visits and Member Discounts throughout the year.' WHERE id = 'plan:hvac';
UPDATE pricing_items SET label = 'Plumbing Care Plan', short_label = 'Plumbing', description = 'A yearly checkup for your water heater and plumbing, plus member savings.' WHERE id = 'plan:plumbing';
UPDATE pricing_items SET label = 'Bundled Care Plan', short_label = 'Bundled', description = 'Full HVAC and plumbing coverage together in one membership.' WHERE id = 'plan:bundled';
UPDATE pricing_items SET label = 'Premier Care Plan', short_label = 'Premier', description = 'Our top-tier membership: everything in Bundled, with after-hours savings and lower service fees.' WHERE id = 'plan:premier';
UPDATE pricing_items SET label = '# of HVAC Systems', short_label = NULL, description = 'Have more than one HVAC system at your property? This add-on extends your plan''s seasonal inspections and filter coverage to each additional system, so every unit gets the same care as your first.' WHERE id = 'addon:hvacSystems';
UPDATE pricing_items SET label = 'Quarterly Filter Change', short_label = NULL, description = 'Your home receives four filter change visits per year, so your HVAC system stays clean, efficient, and well-maintained throughout the seasons.' WHERE id = 'addon:qfc';
UPDATE pricing_items SET label = 'Mini-Split Tune-Up', short_label = NULL, description = 'Each of your mini-split units receives a professional tune-up during your HVAC care plan visit, keeping every room in your home comfortable and your equipment running at its best.' WHERE id = 'addon:mst';
UPDATE pricing_items SET label = '# of Water Heaters', short_label = NULL, description = 'Have more than one water heater at your property? This add-on extends your plan''s annual service visit to each additional unit, so every water heater gets the same care as your first.' WHERE id = 'addon:waterHeaters';
UPDATE pricing_items SET label = 'Water Softener Service', short_label = NULL, description = 'Your water softener is professionally inspected and serviced during your annual plumbing visit, helping protect your plumbing, appliances, and water quality throughout the year.' WHERE id = 'addon:wsv';
UPDATE pricing_items SET label = 'Water Softener Salt', short_label = NULL, description = 'Your technician will top off your water softener with salt during the visit and leave extra bags on hand — so you''re covered between visits without the extra trip to the store.' WHERE id = 'addon:wss';
UPDATE pricing_items SET label = 'Reverse Osmosis Service', short_label = NULL, description = 'Your RO system is professionally serviced during your annual plumbing visit, keeping it operating at peak performance for cleaner, better-tasting water all year long.' WHERE id = 'addon:ros';
UPDATE pricing_items SET label = 'Tankless Water Heater Flush', short_label = NULL, description = 'Your tankless water heater receives a professional chemical descaling flush each year, clearing out mineral buildup to keep it running efficiently and extend its lifespan.' WHERE id = 'addon:twf';
UPDATE pricing_items SET label = 'Quarterly Sediment Filter Change', short_label = NULL, description = 'For homes with a qualifying sediment filtration system. Includes replacement of one poly string-wound sediment filter every three months, up to four times per year.' WHERE id = 'addon:qbb';
-- END GENERATED CATALOG TEXT
